# credentials.py

# Twitter API Credentials
BEARER_TOKEN = "AAAAAAAAAAAAAAAAAAAAAIjX4wEAAAAAzrYlRpqjR3ii57Rh5aOuLvvXUp0%3DFTzBHkelvHmgxvRLBEECa8DqtotPHxnWelwXivXaNnzNqYIMdR"
CONSUMER_KEY = "Y5NIsiiXhgQFspkM89YeQuVTg2"
CONSUMER_SECRET = "TJLL4YHArLxi6nA2N3XLNRExvpxLXbDeJ8G4D18cwWhmXCBOuj"
ACCESS_TOKEN = "1980906500714631168-A8FzcrVa7IOPq3HWAjjdhzRaOKBNn4"
ACCESS_TOKEN_SECRET = "iHPiYUaBtfZHsM0Qos35dgaBUEt39fxPaKWzOxPGdXrvg"

# YouTube API Key
YOUTUBE_API_KEY = "AIzaSyBdlKL1nMpt0ZWlqaP8UxKPYntgIYPSBSY"

# Slack Webhook URL
SLACK_WEBHOOK_URL = "https://hooks.slack.com/services/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"

# Reddit API Credentials
REDDIT_CLIENT_ID = "OZNGNUDxqBEaByhwd52XkA"
REDDIT_CLIENT_SECRET = "S_QIbnR-6yMCCmIocC_9JQB4kq1l0A"
REDDIT_USERNAME = "Extreme_History_4990"
REDDIT_PASSWORD = "H7@7r8p2"

